(function(g){var window=this;'use strict';var Atb=function(a,b){a.fb("onAutonavCoundownStarted",b)},i6=function(a,b,c){g.uv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Zg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.vS&&(b.lengthText?(e=b.lengthText||null,f=b.Dw||null):b.lengthSeconds&&(e=g.AG(b.lengthSeconds),f=g.AG(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.aTa(d).type;var l=b instanceof g.vS?b.isLivePlayback:null,m=b instanceof g.vS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.JJ("Regarder $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Nk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.us};b instanceof g.uS&&(c.playlist_length=b.playlistLength);a.update(c)},j6=function(a){var b=a.U(),c=b.D;
g.W.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],xa:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],xa:"En direct"},
{I:"div",Ka:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",xa:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.J=
a;this.suggestion=null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},k6=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.W({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.O(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
xa:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],xa:"En direct"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});
g.O(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.vT);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({I:"div",S:"ytp-autonav-overlay"});g.O(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.W({I:"div",S:"ytp-autonav-endscreen-button-container"});g.O(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.W({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.O(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.g3,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.W({I:"a",Ka:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},xa:"Regarder"});g.O(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.vT,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Btb(this,b)):this.J.createClientVe(this.playButton.element,
this,115130);this.D=new g.cv(function(){Ctb(c)},500);
g.O(this,this.D);this.uT();this.T(a,"autonavvisibility",this.uT);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.f3),this.T(a,"onAutonavCoundownStarted",this.b$))},l6=function(a){var b=a.J.An(!0,a.J.isFullscreen());
g.uv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Lg(b));g.uv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.jL);g.uv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Hf());g.uv(a.J.getRootNode(),"countdown-running",a.Sk());g.uv(a.container.element,"ytp-player-content",a.J.Hf());g.xs(a.overlay.element,{width:b.width+"px"});if(!a.Sk()){a.J.Hf()?Dtb(a,Math.round(Etb(a)/1E3)):Dtb(a);b=!!a.suggestion&&!!a.suggestion.us;var c=a.J.Hf()||!b;
g.uv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.uv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.BF(a.B,a.J.Hf());g.uv(a.element,"ytp-enable-w2w-color-transitions",Ftb(a))}},Ctb=function(a){var b=Etb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Dtb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Sk()?a.select(!0):a.Sk()&&a.D.start()},Etb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.gC;return-1===a||void 0===a?8E3:a}return 0<=a.J.Qs()?a.J.Qs():g.WI(a.J.U().experiments,"autoplay_time")||1E4},Btb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.M9;a.G=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Ftb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Dtb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.Qf(a);if(0<=b){b=String(b);var c="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Prochaine vid\u00e9o dans $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Jf("Prochaine vid\u00e9o dans $SECONDS".slice(0,d)));var e=g.If("span");g.iv(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Vf(e,b);a.appendChild(e);a.appendChild(g.Jf("Prochaine vid\u00e9o dans $SECONDS".slice(d+c.length)));return}}g.Vf(a,"\u00c0 suivre")},
m6=function(a,b){g.W.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},n6=function(a){g.W.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",xa:"\u00c0 suivre"},{I:"span",S:"ytp-upnext-title",xa:"{{title}}"},{I:"span",S:"ytp-upnext-author",xa:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
xa:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.G=this.Fa("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.cv(this.HH,5E3,this);this.B=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.W({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.O(this,this.cancelButton);this.cancelButton.listen("click",this.j3,this);this.cancelButton.Ja(b);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.O(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.l3);this.api.createClientVe(b,this,115130);this.wT();this.T(a,"autonavvisibility",this.wT);this.T(a,"mdxnowautoplaying",this.N$);this.T(a,"mdxautoplaycanceled",this.O$);g.uv(this.element,"ytp-upnext-mobile",this.api.U().B)},Gtb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.gC;return-1===a||void 0===a?8E3:a}return 0<=a.api.Qs()?a.api.Qs():g.WI(a.api.U().experiments,"autoplay_time")||1E4},Htb=function(a,b){b=Gtb(a,b);
var c=Math,d=c.min;var e=(0,g.YC)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Sk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Sk()&&a.j.start()},o6=function(a){m6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"Plus de vid\u00e9os"}]});this.N=new g.W({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new k6(this.player);g.O(this,this.B);this.B.Ja(this.element);a.getVideoData().Pf?this.j=this.B:(this.j=new n6(a),g.bU(this.player,this.j.element,4),g.O(this,this.j));this.overlay=new g.W({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.O(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.uK(this);g.O(this,this.D);g.O(this,this.table);this.table.Ja(this.element);this.table.show();g.O(this,this.N);this.N.Ja(this.table.element);this.hide()},p6=function(a){var b=a.Hf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},q6=function(a,b){g.W.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],xa:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.o0();2===this.buttonType&&g.pv(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.o0);g.BF(this,!0)},r6=function(a,b){m6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Re=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new q6(a,2);g.O(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},Itb=function(a){m6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",xa:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.O(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.ZV("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.Cl,b.subscribed,"trailer-endscreen",null,a,!1);g.O(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},s6=function(a){var b=a.U(),c=g.sK||g.GR?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",Ka:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",xa:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",xa:"En direct"},{I:"span",S:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",xa:"{{playlist_length}}"},")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.uK(this);g.O(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},t6=function(a){m6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.uK(this);g.O(this,this.B);this.K=new g.cv(function(){g.pv(b.element,"ytp-show-tiles")},0);
g.O(this,this.K);var c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Pr\u00e9c\u00e9dente"},V:[g.HF()]});g.O(this,c);c.Ja(this.element);c.listen("click",this.q3,this);this.table=new g.yF({I:"div",S:"ytp-endscreen-content"});g.O(this,this.table);this.table.Ja(this.element);c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Suivante"},V:[g.IF()]});g.O(this,c);c.Ja(this.element);c.listen("click",this.o3,this);a.getVideoData().Pf?this.j=new k6(a,
!0):this.j=new n6(a);g.O(this,this.j);g.bU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},u6=function(a){return g.cU(a.player)&&a.YC()&&!a.D},v6=function(a){var b=a.Hf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},w6=function(a){m6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new q6(a,1);g.O(this,this.watchButton);this.watchButton.Ja(this.element);g.Thb(a)&&(this.j=new g.i2(a),g.O(this,this.j),this.B=new g.W({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.O(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},Mtb=function(a){g.qV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.uK(this);g.O(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.ZB(g.PR(c))&&d&&!g.ZT(a)?(this.B=!0,this.endScreen=new r6(a,g.PT(a))):a.Yc()?this.endScreen=new w6(a):Jtb(a)?(this.D=!0,Ktb(this),this.j?this.endScreen=new o6(a):this.endScreen=new t6(a)):c.Qg?this.endScreen=new Itb(a):this.endScreen=new m6(a);g.O(this,this.endScreen);g.bU(a,this.endScreen.element,4);Ltb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.DJ("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.EJ("endscreen"),function(e){b.onCueRangeExit(e)})},Ktb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Kl&&a.C===b.Pf)return!1;a.j=b.Kl;a.C=b.Pf;return!0},Jtb=function(a){a=a.U();
return a.ud&&!a.Qg},Ltb=function(a){a.player.rf("endscreen");
var b=a.player.getVideoData();b=new g.CJ(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.CJ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.kf([b,c])};
g.UT.prototype.Qs=g.fa(15,function(){return this.app.Qs()});
g.K0.prototype.Qs=g.fa(14,function(){return this.getVideoData().MV});
g.QT.prototype.Hr=g.fa(13,function(a){this.zi().Hr(a)});
g.vW.prototype.Hr=g.fa(12,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.DX.prototype.Hr=g.fa(11,function(a){this.overflowButton&&this.overflowButton.Hr(a)});
g.QT.prototype.Ir=g.fa(10,function(a){this.zi().Ir(a)});
g.AW.prototype.Ir=g.fa(9,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.DX.prototype.Ir=g.fa(8,function(a){this.shareButton&&this.shareButton.Ir(a)});
g.QT.prototype.BB=g.fa(7,function(a){this.zi().BB(a)});
g.SV.prototype.BB=g.fa(6,function(a){this.eR!==a&&(this.eR=a,this.fq())});
g.QT.prototype.AB=g.fa(5,function(a){this.zi().AB(a)});
g.DX.prototype.AB=g.fa(4,function(a){this.dR!==a&&(this.dR=a,this.eq())});g.y(j6,g.W);j6.prototype.select=function(){this.J.Ho(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tD||void 0)&&this.J.logClick(this.element)};
j6.prototype.onClick=function(a){g.tU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
j6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.y(k6,g.W);g.k=k6.prototype;g.k.QG=function(a){this.suggestion!==a&&(this.suggestion=a,i6(this.j,a),this.playButton.updateValue("url",this.suggestion.Nk()),l6(this))};
g.k.Sk=function(){return 0<this.C};
g.k.IB=function(){this.Sk()||(this.C=Date.now(),Ctb(this),Atb(this.J,Etb(this)),g.uv(this.J.getRootNode(),"countdown-running",this.Sk()))};
g.k.jx=function(){this.Zp();Ctb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.Vf(a,"\u00c0 suivre")};
g.k.Zp=function(){this.Sk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Zp()};
g.k.vT=function(a){g.tU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.fb("innertubeCommand",this.G),this.Zp()):this.select())};
g.k.g3=function(){this.J.logClick(this.cancelButton.element);g.WT(this.J,!0);this.cancelCommand&&this.J.fb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Btb(this,b);var c;this.cancelCommand=null==(c=b.X8)?void 0:c.command};
g.k.b$=function(a){if(Ftb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.IG(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.IG(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.IG(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.IG(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.IG(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.IG(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.uv(this.element,"ytp-w2w-animate",!0)}};
g.k.f3=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.uv(this.element,"ytp-w2w-animate",!1)};
g.k.uT=function(){var a=this.J.Hf();this.K&&this.Bb!==a&&g.BF(this,a);l6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Lg=function(a){return 400>a.width||459>a.height};g.y(m6,g.W);g.k=m6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.YC=function(){return!1};
g.k.Hf=function(){return!1};
g.k.wY=function(){return!1};g.y(n6,g.W);g.k=n6.prototype;g.k.HH=function(){this.notification&&(this.D.stop(),this.Qc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.QG=function(a){this.suggestion=a;i6(this,a,"hqdefault.jpg")};
g.k.wT=function(){g.BF(this,this.api.Hf());this.api.logVisibility(this.element,this.api.Hf());this.api.logVisibility(this.Fa("ytp-upnext-autoplay-icon"),this.api.Hf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Hf())};
g.k.W$=function(){window.focus();this.HH()};
g.k.IB=function(a){var b=this;this.Sk()||(g.hE("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.B=(0,g.YC)(),this.j=new g.cv(function(){Htb(b,a)},25),Htb(this,a),Atb(this.api,Gtb(this,a)));
g.rv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Sk=function(){return!!this.j};
g.k.jx=function(){this.Zp();this.B=(0,g.YC)();Htb(this);g.pv(this.element,"ytp-upnext-autoplay-paused")};
g.k.Zp=function(){this.Sk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.HH(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.Zg()}),this.C=this.T(this.notification,"click",this.W$),this.D.start())}this.Zp();this.api.nextVideo(!1,a)};
g.k.l3=function(a){!g.Uf(this.cancelButton.element,a.target)&&g.tU(a,this.api)&&(this.api.Hf()&&this.api.logClick(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.j3=function(){this.api.Hf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.WT(this.api,!0)};
g.k.N$=function(a){this.api.getPresentingPlayerType();this.show();this.IB(a)};
g.k.O$=function(){this.api.getPresentingPlayerType();this.Zp();this.hide()};
g.k.va=function(){this.Zp();this.HH();g.W.prototype.va.call(this)};g.y(o6,m6);g.k=o6.prototype;g.k.create=function(){m6.prototype.create.call(this);this.D.T(this.player,"appresize",this.kC);this.D.T(this.player,"onVideoAreaChange",this.kC);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.xT);this.D.T(this.player,"onAutonavCancelled",this.m3);this.onVideoDataChange()};
g.k.show=function(){m6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.WT(this.player,!1);g.cU(this.player)&&this.YC()&&!this.C?(p6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.IB():3===this.videoData.autonavState&&this.j.jx()):(g.WT(this.player,!0),p6(this));this.kC()};
g.k.hide=function(){m6.prototype.hide.call(this);this.j.jx();p6(this)};
g.k.kC=function(){var a=this.player.An(!0,this.player.isFullscreen());p6(this);l6(this.B);g.uv(this.element,"ytp-autonav-cancelled-small-mode",this.Lg(a));g.uv(this.element,"ytp-autonav-cancelled-tiny-mode",this.kJ(a));g.uv(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.xs(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.uv(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.WS(this.videoData);b&&(this.j.QG(b),this.j!==this.B&&this.B.QG(b))}if(a&&a.length)for(b=0;b<Ntb.length;++b){var c=Ntb[b];if(a&&a[c]){this.videos[b]=new j6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,i6(d,c));g.O(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.kC()}};
g.k.xT=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Zp(),this.Bb&&this.kC()):(this.K=!0,this.Hf()&&(2===a?this.j.IB():3===a&&this.j.jx()))};
g.k.m3=function(a){a?this.xT(1):(this.C=null,this.K=!1)};
g.k.YC=function(){return 1!==this.videoData.autonavState};
g.k.Lg=function(a){return(910>a.width||459>a.height)&&!this.kJ(a)&&!(400>=a.width||360>=a.height)};
g.k.kJ=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Hf=function(){return this.Bb&&g.cU(this.player)&&this.YC()&&!this.C};
var Ntb=[1,3,2,4];g.y(q6,g.W);g.k=q6.prototype;g.k.o0=function(){switch(this.buttonType){case 1:var a="Regarder \u00e0 nouveau sur YouTube";var b=156915;break;case 2:a="Continuer \u00e0 regarder sur YouTube";b=156942;break;default:a="Continuer \u00e0 regarder sur YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.uU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.HR(b)){var c={};g.HR(b)&&g.JT(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.eP(c,b);a=g.Jn(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Bb&&this.Z)};
g.k.show=function(){g.W.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.logVisibility()};
g.k.Ic=function(a){g.W.prototype.Ic.call(this,a);this.logVisibility()};g.y(r6,m6);r6.prototype.show=function(){3!==this.player.getPlayerState()&&(m6.prototype.show.call(this),this.Re.AB(!0),this.Re.Ir(!0),this.J.U().ye||this.Re.Hr(!0),this.J.logVisibility(this.element,!0),this.watchButton.Ic(!0))};
r6.prototype.hide=function(){m6.prototype.hide.call(this);this.Re.AB(!1);this.Re.Ir(!1);this.Re.Hr(!1);this.J.logVisibility(this.element,!1);this.watchButton.Ic(!1)};g.y(Itb,m6);Itb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Cl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.y(s6,g.W);s6.prototype.select=function(){this.api.Ho(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.tD||void 0)&&this.api.logClick(this.element)};
s6.prototype.onClick=function(a){if(g.HR(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Nk(),c={};g.uVa(this.api,c,"emb_rel_end");b=g.Jn(b,c);g.uU(b,this.api,a)}else g.tU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
s6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
s6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Jf?!1:b.D};g.y(t6,m6);g.k=t6.prototype;g.k.create=function(){m6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.kq();this.B.T(this.player,"appresize",this.kq);this.B.T(this.player,"onVideoAreaChange",this.kq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.YL);this.B.T(this.player,"onAutonavCancelled",this.n3);a=this.videoData.autonavState;a!==this.Y&&this.YL(a);this.B.T(this.element,"transitionend",this.rba)};
g.k.destroy=function(){g.nC(this.B);g.wb(this.stills);this.stills=[];m6.prototype.destroy.call(this);g.rv(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.YC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Bb;m6.prototype.show.call(this);g.rv(this.element,"ytp-show-tiles");this.player.U().B?g.ev(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.WT(this.player,!1);u6(this)?(v6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.IB():3===this.videoData.autonavState&&this.j.jx()):(g.WT(this.player,!0),v6(this));a!==this.Bb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Bb;m6.prototype.hide.call(this);this.j.jx();v6(this);a!==this.Bb&&this.player.logVisibility(this.element,!1)};
g.k.rba=function(a){a.target===this.element&&this.kq()};
g.k.kq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.WS(d)];if(e.length){g.pv(this.element,"ytp-endscreen-paginate");var f=this.J.An(!0,this.J.isFullscreen());if(a=g.PT(this.J))a=a.Bh()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Hs(f,n,p);g.xs(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.QG(g.WS(this.videoData));this.j instanceof
k6&&l6(this.j);g.uv(this.element,"ytp-endscreen-takeover",u6(this));v6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.Je(q+this.C,c),0!==t){r=this.stills[h];r||(r=new s6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var w=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-v-4,C=Math.floor(n*(l+t)/a)-w-4;g.Ds(r.element,w,v);g.Hs(r.element,C,A);g.xs(r.element,"transitionDelay",
(m+l)/20+"s");g.uv(r.element,"ytp-videowall-still-mini",1===t);g.uv(r.element,"ytp-videowall-still-large",2<t);t=Math.max(C,A);g.uv(r.element,"ytp-videowall-still-round-large",256<=t);g.uv(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.uv(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.ov(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",i6(r,q,v),g.HR(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Nk(),v={},g.JT(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.Jn(t,g.eP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.uv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Sf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(null!=a&&g.WS(a)?(this.C=0,this.videoData=a,this.kq()):this.player.ma("missg",{vid:(null==a?void 0:a.videoId)||"",cpn:(null==a?void 0:a.clientPlaybackNonce)||""}))};
g.k.o3=function(){this.C+=this.stills.length;this.kq()};
g.k.q3=function(){this.C-=this.stills.length;this.kq()};
g.k.wY=function(){return this.j.Sk()};
g.k.YL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Zp(),this.Bb&&this.kq()):(this.G=!0,this.Bb&&u6(this)&&(2===a?this.j.IB():3===a&&this.j.jx()))};
g.k.n3=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.YL(1)}else this.D=null,this.G=!1;this.kq()};
g.k.Hf=function(){return this.Bb&&u6(this)};g.y(w6,m6);w6.prototype.iE=function(){var a;return null==(a=this.j)?void 0:a.iE()};
w6.prototype.show=function(){if(3!==this.player.getPlayerState()){m6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.iE();g.uv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.PT(this.player))||c.BB(!0);this.player.logVisibility(this.element,!0);this.watchButton.Ic(!0)}};
w6.prototype.hide=function(){m6.prototype.hide.call(this);var a;null==(a=g.PT(this.player))||a.BB(!1);this.player.logVisibility(this.element,!1);this.watchButton.Ic(!1)};g.y(Mtb,g.qV);g.k=Mtb.prototype;g.k.fu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.Yc()||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.WS(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Jtb(this.player)||d;a=a.xk;c=this.player.HD();return d&&!a&&!c&&!b};
g.k.Hf=function(){return this.endScreen.Hf()};
g.k.P8=function(){return this.Hf()?this.endScreen.wY():!1};
g.k.va=function(){this.player.rf("endscreen");g.qV.prototype.va.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.xb().Fe.get("heartbeat"),d=g.WS(a);!d||b.videoId!==d.videoId||a.rT?(this.player.Ho(b.videoId,void 0,void 0,!0,!0,b),c&&c.wJ("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.qV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.qV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.fu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Ltb(this);this.D&&Ktb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new o6(this.player):this.endScreen=new t6(this.player),g.O(this,this.endScreen),g.bU(this.player,this.endScreen.element,4))};g.pV("endscreen",Mtb);})(_yt_player);
